name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Lists the docker images
      run: docker images 
    - uses: AImiGh7y/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: './Dockerfile'
        image_name: 'academy'
        tag_name: 'latest'
    - uses: AImiGh7y/academy/.github

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - uses: AImiGh7y/academy/.github/actions/docker_hub_push@main 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}